### ISSUE TITLE
Missing basecamp

### ISSUE THREAD

**Issue by eedavidwu** [granularai/chip_segmentation_fabric#11]
The code cannot run without the 'basecamp'.....

**Comment by sagarverma** [comment]
To reproduce IGARSS2019 paper use [igarss2019 branch](https://github.com/granularai/chip_segmentation_fabric/tree/igarss2019).

**Comment by sagarverma** [comment]
If you want to use basecamp and all its feature, we will be happy to provide you the codebase by end of next month. We are making basecamp for rapid research in GeoAI.
